"""create favorite doctor table

Revision ID: bd320dc825fe
Revises: 25fbd1bffbc2
Create Date: 2025-03-27 13:07:51.492095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd320dc825fe'
down_revision = '25fbd1bffbc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
